### ISSUE TITLE
Display Lunar Date

### ISSUE THREAD

**Issue by kimhim** [phannaly/php-datetime-khmer#14]
Please kindly let me now how to custom this extension to show lunar date because of Khmer official document need to use it.
for example: ថ្ងៃចន្ទ ១ រោជ ខែភទ្របត្រ ឆ្នាំម្សាញ់ ព.ស ២៥៦៥
![sses](https://user-images.githubusercontent.com/7098345/132732834-c0098e98-ff12-4e8d-a92a-871038eba00c.PNG)
Thanks in advance for your answer.

**Comment by phannaly** [comment]
I'm moving from PHP for a while. Currently, this lib didn’t support Lunar. For my suggestion, you should list of months in the Lunar date and then call the index as I use it to convert the month into Khmer number.
