### ISSUE TITLE
Get Reverse Date is not working

### ISSUE THREAD

**Issue by limsocheat** [phannaly/php-datetime-khmer#6]
`{{ KhmerDatetime::with(date("Y/m/d", strtotime($schedule->date)))->getDate('reverse') }}`

output: 
'Y/m/d'

**Comment by Chanty-SOK** [comment]
Phanna\Converter\KhmerDatetime::with(date('Y/m/d', strtotime('2020/02/09')))->getDate('revers')
Output: 
**០៩/កុម្ភៈ/២០២០**
This method Work Correctly.

**Comment by phannaly** [comment]
@limsocheat moving from PHP to Ruby, I almost forget this small package. As I remember I call it `revers` not `reverse`. Maybe need to fix typo
